trigger:
- main

pool:
  name: test-agent

steps:

- task: TerraformInstaller@1
  displayName: Install Terraform
  inputs:
    terraformVersion: latest

- script: terraform version
  displayName: Check Terraform Version

# Terraform Init
- task: TerraformTaskV4@4
  displayName: Terraform Init
  inputs:
    provider: azurerm
    command: init
    workingDirectory: $(System.DefaultWorkingDirectory)
    backendServiceArm: test-pipeline-svc

    backendAzureRmResourceGroupName: alpha-rg
    backendAzureRmStorageAccountName: apnastrg789
    backendAzureRmContainerName: apna-container
    backendAzureRmKey: pipeline.tfstate

# Terraform Validate
- task: TerraformTaskV4@4
  displayName: Terraform Validate
  inputs:
    provider: azurerm
    command: validate
    workingDirectory: $(System.DefaultWorkingDirectory)

# Terraform Plan
- task: TerraformTaskV4@4
  displayName: Terraform Plan
  inputs:
    provider: azurerm
    command: plan
    workingDirectory: $(System.DefaultWorkingDirectory)
    commandOptions: "-var-file=terraform.tfvars"
    environmentServiceNameAzureRM: test-pipeline-svc

# Terraform Apply
- task: TerraformTaskV4@4
  displayName: Terraform Apply
  inputs:
    provider: azurerm
    command: apply
    workingDirectory: $(System.DefaultWorkingDirectory)
    commandOptions: "-auto-approve -var-file=terraform.tfvars"
    environmentServiceNameAzureRM: test-pipeline-svc